# Site settings
title: 皆の意見交流所公式ブログ
email: ありません
description: 皆の意見交流所というDiscordサーバーの公式ブログです！
baseurl: "/linuxcodevblog/" # the subpath of your site, e.g. /blog/
url: "http://linuxcodevserver.github.io" # the base hostname & protocol for your site
github_username: linuxcodevserver

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: 皆の意見交流所公式サイト
    link: https://linuxcodevserver.github.io

# Build settings
markdown: kramdown
